PalletTown_PlayersHouse_2F_Text_PlayedWithNES::
    .string "{PLAYER} played with the NES.\p"
    .string "…Okay!\n"
    .string "It's time to go!$"

PalletTown_PlayersHouse_2F_Text_PressLRForHelp::
    .string "It's a posted notice…\p"
    .string "If you're confused, use HELP mode\n"
    .string "and press the L or R Button!\p"
    .string "Too advanced for HELP mode?\p"
    .string "Then register multiple key items\n"
    .string "with the L or R Buttons!\p"
    .string "Want to run fast all the time?\n"
    .string "Equip running shoes and toggle B!$"

