CeruleanCity_House3_Text_PleaseTradeWithMyHusband::
    .string "My husband likes trading POKéMON.\p"
    .string "You're collecting POKéMON for your\n"
    .string "POKéDEX, aren't you?\p"
    .string "Would you please trade with him?$"

CeruleanCity_House3_Text_HavePokemonWillYouTakeIt:
	.string "You're just the TRAINER I'm looking\n"
	.string "for. I have a POKéMON here, but I\l"
	.string "personally don't have time for it.\p"
	.string "Will you take this POKéMON?$"

CeruleanCity_House3_Text_AsYouWishThen:
	.string "If you have a change of heart about\n"
	.string "taking this POKéMON, I will be here.$"

CeruleanCity_House3_Text_ReceivedCharmander:
	.string "{PLAYER} received a Charmander!$"

CeruleanCity_House3_Text_ReceivedBulbasaur:
	.string "{PLAYER} received a Bulbasaur!$"

CeruleanCity_House3_Text_ReceivedSquirtle:
	.string "{PLAYER} received a Squirtle!$"
